# test_pipeline.py — your permanent test harness
# This is NOT production code. It's a realistic fake pipeline
# that deliberately contains the inefficiencies ChainOpt should detect.
# this file was generated by Claude and is not finished at this time
# TODO: finish this file
# - Sim.ai should also be used to create test pipelines

from openai import OpenAI
client = OpenAI()

def process_document(doc_text: str):
    
    # Step 1: Extract key entities
    entities = client.chat.completions.create(
        model="gpt-4o",  # DELIBERATE OVERSIZING — gpt-4o-mini would do this
        messages=[{"role": "user", "content": f"Extract named entities from: {doc_text}"}]
    )
    
    # Step 2: Summarize the document
    summary = client.chat.completions.create(
        model="gpt-4o",
        messages=[{"role": "user", "content": f"Summarize this document: {doc_text}"}]
    )
    
    # Step 3: Extract key entities AGAIN — DELIBERATE REDUNDANCY
    # Same prompt, same input, called twice in the same pipeline
    entities_again = client.chat.completions.create(
        model="gpt-4o",
        messages=[{"role": "user", "content": f"Extract named entities from: {doc_text}"}]
    )
    
    # Step 4 and 5: Two calls with no dependency on each other
    # DELIBERATE PARALLELIZATION OPPORTUNITY
    sentiment = client.chat.completions.create(
        model="gpt-4o-mini",
        messages=[{"role": "user", "content": f"What is the sentiment of: {doc_text}"}]
    )
    
    keywords = client.chat.completions.create(
        model="gpt-4o-mini",
        messages=[{"role": "user", "content": f"Extract keywords from: {doc_text}"}]
    )
    
    return {
        "entities": entities.choices[0].message.content,
        "summary": summary.choices[0].message.content,
        "sentiment": sentiment.choices[0].message.content,
        "keywords": keywords.choices[0].message.content
    }